#!/bin/bash

for i in \
NH3-NH3 NH3-CA NH3-AMD NH3-PHA NH3-PHB \
NH3-PHC NH3-COO CA-CA CA-AMD CA-PHA \
CA-PHB CA-PHC CA-COO AMD-AMD AMD-PHA \
AMD-PHB AMD-PHC AMD-COO PHA-PHA PHA-PHB \
PHA-PHC PHA-COO PHB-PHB PHB-PHC PHB-COO \
PHC-PHC PHC-COO COO-COO
do
sbatch fm-scripts/run_FM_$i.sh
done
